-- Intentionally empty.
--
-- A database reset must create schema and fixed platform resources only. Instance,
-- admin, demo, and smoke data are parameterized outside SQL:
--
--   pnpm bootstrap:instance         # required tenant + first admin
--   pnpm seed:optional              # optional idempotent demo catalog
--   pnpm smoke:bootstrap            # optional local smoke identities
--
-- Keeping this file allows `supabase db reset --local` to retain the standard
-- Supabase seed phase without coupling a fresh database to a tenant UUID.
